### ISSUE TITLE
Warning of deprecated use

### ISSUE THREAD

**Issue by eccles** [tim-actions/commit-message-checker-with-regex#15]
I am using this and notice the following warning:

Run tim-actions/get-pr-commits@master
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by eccles** [comment]
And another warning:

The following actions uses node12 which is deprecated and will be forced to run on node16: tim-actions/commit-message-checker-with-regex@v0.3.1. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/

**Comment by kolyshkin** [comment]
dup of #8

**Comment by Tim-Zhang** [comment]
Release v0.3.2 should fix this.
