### ISSUE TITLE
Last version is `v0.3.1`, but the highest SemVer tag is `v1`

### ISSUE THREAD

**Issue by kolyshkin** [tim-actions/commit-message-checker-with-regex#4]
There is a tag 'v1' in this repo (https://github.com/tim-actions/commit-message-checker-with-regex/releases/tag/v1)
which I think needs to be removed as the latest version is v0.3.1 and v1 > v0,
so dependabot suggest to update from v0.3.1 to v1 which is obviously wrong.

Here is the dependabot PR illustrating the problem: https://github.com/opencontainers/runc/pull/2979#issuecomment-852731512

To fix this, `v1` tag need to be removed, or you can release say `v1.1.0` (or so).
In both cases, an update to README.md is required.

**Comment by Tim-Zhang** [comment]
@kolyshkin I have removed the tag v1, thank you very much.
