### ISSUE TITLE
`one_pass_all_pass` vs `checkAllCommitMessages`?

### ISSUE THREAD

**Issue by tony** [tim-actions/commit-message-checker-with-regex#5]
The current tip of https://github.com/GsActions/commit-message-checker has `checkAllCommitMessages`. Is there a difference in how this one is intended to handle the case?

**Comment by Tim-Zhang** [comment]
@tony the `one_pass_all_pass` means if one commit in the pull request commits hit the rule, then the whole check passes

we have no option `checkAllCommitMessages`, because we will check all commits by default and we do not check pull request titles.
