### ISSUE TITLE
Node 12 Actions are deprecated

### ISSUE THREAD

**Issue by gesellix** [tim-actions/commit-message-checker-with-regex#8]
See https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

The action should be upgraded to Node 16.

**Comment by skitt** [comment]
This was fixed by #12.

**Comment by dfarrell07** [comment]
This can be closed IMHO. :heavy_check_mark:

**Comment by kolyshkin** [comment]
> This can be closed IMHO. heavy_check_mark

Not until a release is made. @Tim-Zhang can you please tag a new release?

**Comment by kolyshkin** [comment]
@Tim-Zhang can you please tag a new release?

**Comment by Tim-Zhang** [comment]
@kolyshkin @gesellix A new release has been tagged
